// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjohpbqnatrwcqxnhgrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqb2hwYnFuYXRyd2NxeG5oZ3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzOTQ1MTEsImV4cCI6MjA5MTk3MDUxMX0.zsD9j8XBN7IHbxMUH9nGCNz36gu_mGa5J2NB7BMWJvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});